set -g default-terminal "xterm-256color"
set -g mouse on
set-window-option -g mode-keys vi

# vim-like movements
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# reload from source-file with r
bind r source-file ~/.tmux.conf

# copy to clipboard
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"

# make mouse scrolling work
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -sg escape-time 1

# Undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0
